apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui.name" . }}-svc
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ui.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}