apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ui.name" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.ingress.enforceSsl  }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{ end }}
spec:
  rules:
    - host: {{ .Values.ingress.dns }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ui.name" . }}-svc
                port:
                  number: {{ .Values.service.port }}