apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.psql.endpoint }}
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.global.psql.port }}
      targetPort: {{ .Values.global.psql.port }}