apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.postgresSecretName }}
  labels:
    {{- include "postgres-db.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: YXNkZg==