apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.psql.endpoint }}
  labels: 
    {{- include "postgres-db.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "postgres-db.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.global.psql.port }}
      targetPort: {{ .Values.global.psql.port }}